export const SET_USER_TOKEN = "SET_USER_TOKEN";

export const GET_MESSAGES = "GET_MESSAGES";
export const GET_CONVERSATIONS = "GET_CONVERSATIONS";

export const SET_MESSAGES = "SET_MESSAGES";
export const SET_CONVERSATIONS = "SET_CONVERSATIONS";

export const EXIT_CURRENT_CHAT = "EXIT_CURRENT_CHAT";

export const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE";

export const CREATE_NEW_CONNECTION = "CREATE_NEW_CONNECTION";
export const SET_ONLINE_USERS_LIST = "SET_ONLINE_USERS_LIST";

export const ADD_NEW_MESSAGE_TO_ARRAY = "ADD_NEW_MESSAGE_TO_ARRAY";
