export const CHANGE_CHAT_STATE = "CHANGE_CHAT_STATE";
export const SET_ACTIVE_CHAT_MESSAGES = "SET_ACTIVE_CHAT_MESSAGES";
export const SEND_MESSAGE = " SEND_MESSAGE";

export const SET_WEBSOCKET_ACTIVE = "SET_WEBSOCKET_ACTIVE";
export const SET_MESSAGES_FROM_BACKEND = " SET_MESSAGES_FROM_BACKEND";

export const SET_USER_TOKEN = "SET_USER_TOKEN";

export const SET_MESSAGES = "SET_MESSAGES";
