export const EXIT_CURRENT_CHAT = "EXIT_CURRENT_CHAT";
export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const GET_MESSAGES = "GET_MESSAGES";
export const ADD_NEW_MESSAGE_TO_ARRAY = "ADD_NEW_MESSAGE_TO_ARRAY";
export const SET_MESSAGES = "SET_MESSAGES";
export const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const LOG_OUT_CHAT = "LOG_OUT_CHAT";
